repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0 # Use the latest stable version
  hooks:
  - id: trailing-whitespace # Removes trailing whitespace
  - id: end-of-file-fixer # Ensures files end with a newline
  - id: check-yaml # Validates YAML files
  - id: check-json # Validates JSON files
